# Generated by Django 5.2.6 on 2025-09-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Adminstrador',
        ),
        migrations.AlterModelTable(
            name='adminstrador',
            table='adminstrador',
        ),
    ]
