# Generated by Django 5.2.6 on 2025-09-25 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0001_initial'),
        ('lares_temporarios', '0002_alter_lartemporario_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicolartemporario',
            name='status',
        ),
        migrations.CreateModel(
            name='LarTemporarioAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.gato', verbose_name='Gato')),
                ('lar_temporario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lares_temporarios.lartemporario', verbose_name='Lar temporário')),
            ],
            options={
                'verbose_name': 'Lar Temporario Atual',
                'verbose_name_plural': 'Lares Temporários Atuais',
                'db_table': 'lar_temporario_atual',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
