# Generated by Django 5.2.6 on 2025-09-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adocao',
            name='cep',
            field=models.IntegerField(verbose_name='CEP'),
        ),
    ]
