# Generated by Django 5.2.6 on 2025-09-25 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0002_alter_adocao_cep'),
        ('gatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adotados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='gatos/', verbose_name='Imagem')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('adocao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adocoes.adocao', verbose_name='Adoção')),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.gato', verbose_name='Gato')),
            ],
            options={
                'verbose_name': 'Adotado',
                'verbose_name_plural': 'Adotados',
                'db_table': 'adotados',
                'ordering': ['-created_at'],
            },
        ),
    ]
