# Generated by Django 5.2.6 on 2025-09-30 17:41

from django.db import migrations

def criar_gato_exemplo(apps, schema_editor):
    Gato = apps.get_model("gatos", "Gato")
    Cuidado = apps.get_model("gatos", "Cuidado")
    Moradia = apps.get_model("gatos", "Moradia")
    Sociavel = apps.get_model("gatos", "Sociavel")
    Temperamento = apps.get_model("gatos", "Temperamento")

    # Criar registros relacionados mínimos
    cuidado = Cuidado.objects.create(castrado=True, vacinado=True)
    moradia = Moradia.objects.create(casa_com_quintal=True)
    sociavel = Sociavel.objects.create(gatos=True, criancas=True)
    temperamento = Temperamento.objects.create(docil=True, brincalhao=True)

    # Criar gato de exemplo
    Gato.objects.create(
        nome="Mimi",
        sexo="F",
        idade="2 anos",
        descricao="Uma gata brincalhona e dócil, ótima companhia.",
        imagem="", 
        lar_temporario=False,
        cuidado=cuidado,
        moradia=moradia,
        sociavel=sociavel,
        temperamento=temperamento,
    )

class Migration(migrations.Migration):

    dependencies = [
        ("gatos", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(criar_gato_exemplo),
    ]
