# Generated by Django 5.2.5 on 2025-10-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='adotado',
            field=models.BooleanField(default=False, verbose_name='Adotado'),
        ),
    ]
