# Generated by Django 5.2.6 on 2025-10-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='descricao',
            field=models.TextField(max_length=10000, verbose_name='Sobre o gato'),
        ),
        migrations.AlterField(
            model_name='gato',
            name='imagem',
            field=models.ImageField(upload_to='gatos/', verbose_name='Foto do gato'),
        ),
        migrations.AlterField(
            model_name='gato',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do gao'),
        ),
    ]
