# Generated by Django 5.2.6 on 2025-10-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0002_gato_adotado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo'),
        ),
    ]
