# Generated by Django 5.2.5 on 2025-10-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0002_gato_adotado'),
        ('gatos', '0002_inserir_gatos_exemplo'),
    ]

    operations = [
    ]
